language: objective-c
osx_image: xcode8.3
sudo: false

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install && cd $TRAVIS_BUILD_DIR

script:
- xcodebuild -workspace DDCollectionViewFlowLayout.xcworkspace -scheme DDCollectionViewFlowLayout -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'
